### ISSUE TITLE
Concurrent create sessions share one preview-renderer jar, and every render rebuilds it

### ISSUE THREAD

**Issue by DemchaAV** [DemchaAV/graphcompose-ai-flow#4]
## Problem

Two concurrent `create` sessions cannot safely share one plugin install, because every full-pipeline render rebuilds a **shared** artifact: `tools/preview-renderer/target/preview-renderer.jar`.

`render-runtime.mjs:112` resolves the renderer from `repoRoot` — the install, not the project:

```js
const previewRendererDir = path.join(repoRoot, "tools", "preview-renderer");
```

and `mvn package` is skipped only for two narrow scopes (`render-runtime.mjs:207`):

```js
const skipMavenPackage =
  !forceFullPipeline &&
  (scope === "data-only" || scope === "asset-only") &&
  fs.existsSync(cachedClasses) &&
  fs.existsSync(previewRendererJar);
```

A `create` is neither, so **every render in a create loop rebuilds the shared jar**. Everything else is properly isolated — the project, its revisions, and `render-runner/target/` all live under `projectDir`, and the Iconify cache is content-addressed with atomic tmp+rename.

## Mechanism — proven

This exact failure was diagnosed and fixed *in the test suite* by 2a896b8 / #3, where `revision-discipline` rebuilt the jar while `import-reference` executed it:

```
java.lang.NoClassDefFoundError: org/apache/pdfbox/contentstream/operator/text/SetTextHorizontalScaling
    at org.apache.pdfbox.rendering.PDFRenderer.createPageDrawer(PDFRenderer.java:528)
    at com.demcha.graphcompose.preview.PreviewCommand.runRenderPages(PreviewCommand.java:113)
Caused by: java.lang.ClassNotFoundException
```

The jar is **never missing** — the shade plugin replaces it atomically, confirmed by polling the path 13,533 times through a full package with zero misses. The hazard is that a JVM loads classes **lazily**: replacing the file under a live process invalidates the handle it has not finished reading from. PDFBox then cannot load a class it only needs for certain content streams — one that was present in the jar when the JVM started.

Two concurrent Maven runs against the same `target/` are a second hazard; Maven takes no lock there.

**What is proven:** the jar-swap kills a running JVM, with the stack trace above captured from a real run.
**What is inferred:** that two concurrent `create` sessions hit the same window. Same mechanism, same shared file, but not separately reproduced.

## Why this is nasty

The symptom is a render failing inside PDFBox with no relation to the template being authored. The agent's most reasonable next move is to go and debug its own Java — the one place the cause is not.

## Proposed fix

Stop rebuilding the shared renderer during a render. The code already has the right behaviour for one case (`render-runtime.mjs:247`):

```
> preview-renderer build skipped (installed copy; using the shipped jar)
```

An installed harness ships the jar and reuses it. A checkout rebuilds every time because its sources exist (`render-runtime.mjs:240`). Options, roughly in order of preference:

1. **Build once in `npm run setup`, reuse thereafter** — treat the renderer like any other built tool. `setup.mjs:117` already packages it. A render would then verify the jar exists and is newer than `src/`, and rebuild only when stale.
2. **Build into a per-session target** so concurrent renders cannot collide.
3. **Lock the build** — narrowest change, but serialises renders across sessions rather than making them independent.

Option 1 also removes a Maven invocation from every render, which is pure latency in the create loop.

## Workarounds until then

- Run template sessions **sequentially**, or
- give each session its **own install** — `claude --plugin-dir <checkout>` per terminal, so `tools/preview-renderer` is not shared. The icon cache duplicates harmlessly; it is content-addressed.

## Note

Deliberately not fixed in #3: that branch was scoped to a test-infrastructure race, and changing when the renderer rebuilds is production behaviour. Fixing tests by moving runtime behaviour would have been the wrong trade.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
